# Generated by Django 3.1.7 on 2021-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='None', max_length=10),
        ),
    ]
