# Generated by Django 3.1.7 on 2021-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210324_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='men_brand',
            field=models.CharField(choices=[('None', 'None'), ('Levi', 'Levi'), ('People Jeans', 'People Jeans'), ('Lee', 'Lee'), ('Adidas', 'Adidas'), ('Flying Machine', 'Flying Machine')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='women_brand',
            field=models.CharField(choices=[('None', 'None'), ('Nishat', 'Nishat'), ('Bareeze', 'Bareeze'), ('Khaadi', 'Khaadi'), ('Limelight', 'Limelight'), ('Maria B', 'Maria B'), ('Gul Ahmed', 'Gul Ahmed'), ('Junaid Jamshed', 'Junaid Jamshed')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='None', max_length=100),
        ),
    ]
