# Generated by Django 3.1.7 on 2021-03-24 20:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='none'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='none'),
        ),
    ]
