# Generated by Django 3.1.7 on 2021-03-24 20:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210325_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(max_length=255),
        ),
    ]
