# Generated by Django 3.1.7 on 2021-03-24 20:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210325_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Write Your long Description here'),
        ),
    ]
