# Generated by Django 3.1.7 on 2021-04-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210408_0149'),
        ('product', '0014_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
