# Generated by Django 3.1.7 on 2021-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210408_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_of_visits',
        ),
        migrations.AddField(
            model_name='comment',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
